# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'notchtest' do
	pod 'lottie-ios'
    pod 'INTUAnimationEngine'                 # Interpoleating value utilities (for playerview shrinking expanding)

   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for notchtest

end
